# Nombre de la aplicación
spring.application.name=discografia

# Configuración de conexión a MongoDB Atlas (Versión Actualizada)
spring.mongodb.uri=mongodb+srv://Pablo:Pablo123@eva-u2-spring.gkrpyua.mongodb.net/discografica-db?retryWrites=true&w=majority&appName=eva-u2-spring
spring.mongodb.database=discografica-db